name: assignment 1 complex workflow

on: [push]

jobs:
  job1:
    name: print_date
    runs-on: ubuntu-latest
    steps:
    - run: date
  job2:
    runs-on: windows-latest
    steps:
    - run: date
  job3:
    runs-on: macos-latest
    steps:
    - run: date
  job4:
    needs: [job1, job2, job3]
    runs-on: windows-2019
    steps:
    - run: date